dist: xenial
language: python
python:
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda create -n psl-dev python=$TRAVIS_PYTHON_VERSION pip
  - source activate psl-dev
  - cd Catalog
  - pip install -r requirements.txt
  - pip install -e .

# command to run tests
script:
- cd catalog_builder && pytest tests/ -v